# Generated by Django 5.2.7 on 2026-08-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='The short code, for example: github', unique=True)),
                ('destination_url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('click_count', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Short URL',
                'verbose_name_plural': 'Short URLs',
                'ordering': ['-created_at'],
            },
        ),
    ]
